# Generated by GitHub Copilot on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_account_profiles(apps, schema_editor):
	User = apps.get_model(settings.AUTH_USER_MODEL.split('.', 1)[0], settings.AUTH_USER_MODEL.split('.', 1)[1])
	AccountProfile = apps.get_model('api', 'AccountProfile')

	for user in User.objects.all().iterator():
		if user.is_superuser:
			role = 'admin'
		elif user.is_staff:
			role = 'staff'
		else:
			role = 'citizen'

		AccountProfile.objects.get_or_create(user_id=user.id, defaults={'role': role})


def remove_account_profiles(apps, schema_editor):
	AccountProfile = apps.get_model('api', 'AccountProfile')
	AccountProfile.objects.all().delete()


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('api', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='AccountProfile',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('citizen', 'Citizen')], db_index=True, default='citizen', max_length=20)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['user__username', 'user__id'],
			},
		),
		migrations.RunPython(create_account_profiles, remove_account_profiles),
	]