# Generated by Django 6.0.4 on 2026-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
