# Generated by Django 6.0.4 on 2026-05-03 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hazard Types',
                'db_table': 'hazard_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('incident_datetime', models.DateTimeField()),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('ongoing', 'Ongoing'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=20)),
                ('impact_level', models.CharField(choices=[('minimal', 'Minimal'), ('minor', 'Minor'), ('major', 'Major'), ('severe', 'Severe'), ('catastrophic', 'Catastrophic')], default='minimal', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='locations.barangay')),
                ('hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.hazardtype')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-incident_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FireDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('damage_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('casualties', models.IntegerField(default=0)),
                ('injuries', models.IntegerField(default=0)),
                ('structures_affected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fire_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'fire_details',
            },
        ),
        migrations.CreateModel(
            name='EarthquakeDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('magnitude', models.DecimalField(decimal_places=1, max_digits=3)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in km', max_digits=6)),
                ('intensity', models.CharField(blank=True, help_text='PEIS intensity scale', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earthquake_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'earthquake_details',
            },
        ),
        migrations.CreateModel(
            name='DrowningIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('victims', models.IntegerField(default=0)),
                ('rescued', models.IntegerField(default=0)),
                ('fatalities', models.IntegerField(default=0)),
                ('water_body', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drowning_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'drowning_incidents',
            },
        ),
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crime_type', models.CharField(max_length=100)),
                ('suspects', models.IntegerField(default=0)),
                ('victims', models.IntegerField(default=0)),
                ('arrested', models.BooleanField(default=False)),
                ('case_status', models.CharField(default='under_investigation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crime_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'crime_reports',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('warning', 'Warning'), ('evacuation', 'Evacuation Order'), ('all_clear', 'All Clear'), ('advisory', 'Advisory')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='incidents.incident')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEmergency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_count', models.IntegerField(default=1)),
                ('emergency_type', models.CharField(max_length=100)),
                ('transported', models.IntegerField(default=0, help_text='Number transported to hospital')),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'medical_emergencies',
            },
        ),
        migrations.CreateModel(
            name='ResponderReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('report_text', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, help_text='Photo/video URL')),
                ('status_update', models.CharField(default='ongoing', max_length=50)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_reports', to='incidents.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responder_reports',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='VehicularAccident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicles_involved', models.IntegerField(default=1)),
                ('casualties', models.IntegerField(default=0)),
                ('injuries', models.IntegerField(default=0)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('vehicle_types', models.TextField(blank=True, help_text='Comma-separated list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicular_accident_details', to='incidents.incident')),
            ],
            options={
                'db_table': 'vehicular_accidents',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_status_9db31b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity_level'], name='incidents_severit_fc446a_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_datetime'], name='incidents_inciden_df75e8_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active'], name='alerts_is_acti_449676_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx'),
        ),
        migrations.AddIndex(
            model_name='responderreport',
            index=models.Index(fields=['report_time'], name='responder_r_report__1b3ea8_idx'),
        ),
    ]
