# Generated by Django 6.0.4 on 2026-05-29 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_add_reference_code'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, help_text='Incident reference code (e.g., INC-2025-001). Auto-generated if blank.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='responderreport',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reference_code'], name='incidents_referen_ea2d9f_idx'),
        ),
    ]
