# Generated by Django 6.0.4 on 2026-05-29 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_reference_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('incident_code', models.CharField(max_length=30)),
                ('time_occurred', models.TimeField()),
                ('incident_type', models.CharField(max_length=100)),
                ('responder_team', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('victim_count', models.PositiveIntegerField(default=0)),
                ('action_taken', models.TextField()),
                ('status', models.CharField(default='Submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccomplishmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compiled_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(default='Accomplishment Report', max_length=100)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Compiled', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident_reports', models.ManyToManyField(related_name='accomplishment_reports', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'accomplishment_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VictimDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('condition', models.TextField()),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'victim_details',
            },
        ),
    ]
