# Generated by Django 6.0.4 on 2026-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentreport_latitude_incidentreport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
