# Generated by Django 6.0.4 on 2026-05-02 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='Lucena City', max_length=200)),
                ('province', models.CharField(default='Quezon', max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('boundary', models.JSONField(blank=True, help_text='GeoJSON geometry (Polygon/MultiPolygon)', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Centroid latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Centroid longitude', max_digits=9, null=True)),
                ('brgy_code', models.CharField(blank=True, max_length=50)),
                ('reg_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'db_table': 'barangays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarthquakeFaultLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('coordinates', models.JSONField(help_text="GeoJSON LineString: {'type': 'LineString', 'coordinates': [[lng,lat], ...]}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earthquake_fault_lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.barangay')),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='locations_latitud_4052bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopulationDensity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('density', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_density_records', to='locations.barangay')),
            ],
            options={
                'verbose_name_plural': 'Population Density Records',
                'db_table': 'population_density',
                'ordering': ['-recorded_at'],
                'unique_together': {('barangay', 'recorded_at')},
            },
        ),
    ]
