# Generated by Django 6.0.4 on 2026-05-04 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Supply Categories',
                'db_table': 'supply_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('rescue_gear', 'Rescue Gear'), ('communication', 'Communication Equipment'), ('medical', 'Medical Equipment'), ('firefighting', 'Firefighting Equipment'), ('water_rescue', 'Water Rescue Equipment'), ('power', 'Power Generation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('asset_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Current storage location', max_length=200)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['equipment_type', 'name'],
                'indexes': [models.Index(fields=['status'], name='equipment_status_92035a_idx'), models.Index(fields=['equipment_type'], name='equipment_equipme_f4cc15_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuation_centers', to='locations.barangay')),
            ],
            options={
                'db_table': 'evacuation_centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilograms'), ('liter', 'Liters'), ('piece', 'Pieces'), ('set', 'Sets'), ('bottle', 'Bottles'), ('sack', 'Sacks')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('depleted', 'Depleted')], default='available', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='resources.supplycategory')),
            ],
            options={
                'db_table': 'supplies',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['status'], name='supplies_status_83b4e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('skills', models.JSONField(default=list, help_text='List of skill codes')),
                ('certifications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_deployment', 'On Deployment')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='locations.barangay')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status'], name='volunteers_status_02c29c_idx'), models.Index(fields=['barangay'], name='volunteers_baranga_15781c_idx')],
            },
        ),
    ]
